export const allProjects = [
  {
    projectTitle: "eMarket.",
    category: "react",
    imgpath: "/project-img/emarket.png",
    describe: "is an E-Commerce website",
    proURL: "https://github.com/mustafaahmed798/emarket-shop",
    proLink: "https://emarket-shop.netlify.app/",
  },

  {
    projectTitle: "Drag & Drop",
    category: "java",
    imgpath: "/project-img/drag.jpg",
    describe: "Drag & Drop items",
    proURL: "https://github.com/mustafaahmed798/drag-drop",
    proLink: "https://mustafaahmed798.github.io/drag-drop/",
  },
  {
    projectTitle: "Budgety",
    category: "java",
    imgpath: "/project-img/budgety.png",
    describe: "Calculate the income and expense",
    proURL: "https://github.com/mustafaahmed798/budget",
    proLink: "https://mustafaahmed798.github.io/budget/",
  },
  {
    projectTitle: "Bankist",
    category: "java",
    imgpath: "/project-img/bankist.png",
    describe: "When banking meets minimalist",
    proURL: "https://github.com/mustafaahmed798/bankist",
    proLink: "https://mustafaahmed798.github.io/bankist/",
  },
  {
    projectTitle: "Saus Resturant",
    category: "react",
    imgpath: "/project-img/saus.png",
    describe: "Single page design for a Resturant",
    proURL: "https://github.com/mustafaahmed798/saus-resturant",
    proLink: "https://mustafaahmed798.github.io/saus-resturant/",
  },
  {
    projectTitle: "Todo List",
    category: "react",
    imgpath: "/project-img/todolist.png",
    describe: "Todo list app",
    proURL: "https://github.com/mustafaahmed798/todolist-app",
    proLink: "https://mustafaahmed798.github.io/todolist-app/",
  },
  {
    projectTitle: "CRUD Post",
    category: "react",
    imgpath: "/project-img/crud.jpg",
    describe: "allow to use CRUD operations",
    proURL: "https://github.com/mustafaahmed798/crud",
    proLink: "https://crud-posts.netlify.app/",
  },
];
